language: cpp

sudo: required
dist: xenial

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On"
    - PATH="/usr/local/opt/qt/bin:/usr/local/opt/glbinding:/usr/local/opt/globjects:$PATH"
    
  matrix:
    - CMAKE_CONFIGURATION=release BUILD_DIR=build
    - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug

matrix:
  exclude:
  - os: osx
    compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cppcheck
      - clang-tidy-3.8
      - gcc-5
      - g++-5
      - libfreetype6-dev
      - libpng-dev

before_install:
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH;
  - |-
    if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-add-repository ppa:cginternals/ppa -y;
      sudo apt-add-repository ppa:cginternals/backports-ppa -y;
      sudo apt-get update -qq;
      sudo apt-get install -qq qt5-default libglm-dev libglbinding-dev libglobjects-dev libcpplocate-dev;
    fi  # libpng is already installed by default
  - |-
    if [ $TRAVIS_OS_NAME == osx ]; then
      brew tap cginternals/homebrew-cginternals;
      brew update && brew install cppcheck fontconfig freetype qt5 glm glbinding cginternals/homebrew-cginternals/globjects cginternals/homebrew-cginternals/cpplocate;
      export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;$(brew --prefix qt);$(brew --prefix glm);$(brew --prefix glbinding);$(brew --prefix globjects);$(brew --prefix cpplocate)";
    fi
  - chmod +x ./configure

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc && sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
  - ./configure
  - ./configure $CMAKE_CONFIGURATION

script:
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
  - cmake --build $BUILD_DIR --target check-all
