version: '{build}'
branches:
  only:
  - master
  - debug-appveyor
clone_folder: c:\projects\llassetgen
image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( 
    set generator="Visual Studio 15 2017 %arch%"&&
    set tools=msvc15)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( 
    set generator="Visual Studio 14 2015 %arch%"&& 
    set tools=msvc14)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( 
    set generator="Visual Studio 12 2013 %arch%"&& 
    set tools=msvc12)
- echo %generator%

install:
- mkdir deps
- if "%arch%"=="Win64" (set ver=x64)

- mkdir deps\zlib
- echo install zlib-msvc-%ver%
- nuget install zlib-msvc-%ver%
- ps: move zlib*\*\zlib.lib deps\zlib\zlib.lib -force
- ps: move zlib*\*\include deps\zlib\include -force

- mkdir deps\libpng
- nuget install libpng-msvc-%ver%
- ps : move libpng*\*\libpng16.lib deps\libpng\libpng16.lib -force
- ps : move libpng*\*\include deps\libpng\include -force

- mkdir deps\freetype
- nuget install freetype
- ps: move freetype*\*\x64\v141\static\Release\freetype28.lib deps\freetype\freetype28.lib -force
- ps : move freetype*\*\include deps\freetype\include -force

before_build:
- cmd: >-

    set ZLIB_ROOT=C:\projects\llassetgen\deps\zlib

    set PNG_ROOT=C:\projects\llassetgen\deps\libpng

    set FREETYPE_DIR=C:\projects\llassetgen\deps\freetype
    
    set FREETYPE_INCLUDE_DIRS=C:\projects\llassetgen\deps\freetype\include
    
    set FREETYPE_LIBRARY=C:\projects\llassetgen\deps\freetype\freetype28.lib

    set ZLIB_INCLUDE_DIR=C:\projects\llassetgen\deps\zlib\include

    set ZLIB_LIBRARY_RELEASE=C:\projects\llassetgen\deps\zlib\zlib.lib

    set PNG_PNG_INCLUDE_DIR=C:\projects\llassetgen\deps\libpng\include

    set PNG_LIBRARY_RELEASE=C:\projects\llassetgen\deps\libpng\png.lib

    set PATH=%ZLIB_ROOT%;%PNG_ROOT%;%FREETYPE_DIR%;%PATH%;

    echo %PATH%
    
    mkdir build
    
    cd build
    
    cmake --version

    cmake .. -G %generator% -DZLIB_INCLUDE_DIR=%ZLIB_INCLUDE_DIR% -DZLIB_LIBRARY_RELEASE=%ZLIB_LIBRARY_RELEASE% -DPNG_PNG_INCLUDE_DIR=%PNG_PNG_INCLUDE_DIR% -DPNG_LIBRARY_RELEASE=%PNG_LIBRARY_RELEASE% -DFREETYPE_DIR=%FREETYPE_DIR% -DFREETYPE_LIBRARY=%FREETYPE_LIBRARY% -DFREETYPE_INCLUDE_DIRS=%FREETYPE_INCLUDE_DIRS%
    
build:
  project: c:\projects\llassetgen\build\llassetgen.sln
  verbosity: minimal
  parallel: true 
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - sources/
    - cmake/
