if (WIN32)
	include(cpack-windows-dlls.cmake)
endif()

set(CPACK_GENERATOR NSIS) 
set(CPACK_PACKAGE_NAME "llassetgen")
set(CPACK_PACKAGE_VENDOR "Lukas Behrendt, Anne Gropler, Alexander Meißner, David Stangl, Justin Trautmann")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Font Asset Generator based on OpenLL Specifications")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "llassetgen")

include(CPack)
